language: php

php:
  - 7.2

before_script:
  - composer install -o --no-interaction

script:
  - ./vendor/bin/phpunit
  - php coverage-checker.php log/clover.xml 100

after_success:
  - travis_retry php vendor/bin/coveralls -v
