build: false
shallow_clone: false
platform: 'x86'
clone_folder: C:\projects\better-serializer

cache:
  - C:\projects\better-serializer\vendor -> C:\projects\better-serializer\composer.lock

install:
  - cinst -y OpenSSL.Light
  - SET PATH=C:\Program Files\OpenSSL;%PATH%
  - cinst -y curl
  - SET PATH=C:\Program Files\curl;%PATH%
  - sc config wuauserv start= auto
  - net start wuauserv
  - cinst -y php --version 7.1.13
  - cd c:\tools\php71
  - copy php.ini-production php.ini
  - echo date.timezone="UTC" >> php.ini
  - echo mbstring.http_input=pass >> php.ini
  - echo mbstring.http_output=pass >> php.ini
  - echo extension_dir=ext >> php.ini
  - echo extension=php_mbstring.dll >> php.ini
  - echo extension=php_openssl.dll >> php.ini
  - echo extension=php_curl.dll >> php.ini
  - cd C:\projects\better-serializer
  - SET PATH=C:\tools\php71;%PATH%
  - php -r "readfile('http://getcomposer.org/installer');" | php
  - php composer.phar install --prefer-source --no-interaction

test_script:
  - cd C:\projects\better-serializer
  - vendor\bin\phpunit.bat
