build: false
shallow_clone: false
platform: 'x86'
clone_folder: C:\projects\better-serializer

install:
  - sc config wuauserv start= auto
  - net start wuauserv
  - cinst -y php
  - cd c:\tools\php71
  - copy php.ini-production php.ini
  - echo date.timezone="UTC" >> php.ini
  - echo extension_dir=ext >> php.ini
  - cd C:\projects\better-serializer
  - SET PATH=C:\tools\php71;%PATH%
  - php -r "readfile('http://getcomposer.org/installer');" | php
  - php composer.phar install --prefer-source --no-interaction

test_script:
  - cd C:\projects\better-serializer
  - vendor\bin\phpunit.bat
