version: '3.1'

services:
  # PHP
  bs-php72-cli:
    container_name: bs-php72-cli
    build: ./docker/php
    volumes:
      - .:/opt/project:cached
      - ~/.ssh/id_rsa:/root/.ssh/id_rsa
      - ~/.composer:/root/.composer:cached
    environment:
      - XDEBUG_CONFIG=remote_host=docker.for.mac.host.internal idekey=PHPSTORM
