version: '3.1'

services:
  # PHP
  bs-php71-cli:
    container_name: bs-php71-cli
    build: ./docker/php
    volumes:
      - .:/opt/project:cached
      - ~/.ssh/id_rsa:/root/.ssh/id_rsa
      - ~/.composer:/root/.composer:cached
    environment:
      - SYMFONY_ENV=dev
      - XDEBUG_CONFIG=remote_host=docker.for.mac.host.internal idekey=PHPSTORM
#docker.for.mac.host.internal
